bind '"^[[A":history-search-backward'
bind '"^[[B":history-search-forward'

alias lla='ls -la'
alias go='cd'
alias prev='cd -'
#alias emacs='emacs &'
alias md='mkdir'
alias up='cd ..'
alias home='cd ~/'
alias cls='clear'
function e() { emacs $@ & }
# function n() { 
#    export LANG=en_US
#    nedit $@ &
#    export LANG=en_US.UTF-8
#    }
alias subl='sublime'
alias settings='sublime ~/.bash_aliases'
alias refresh='source ~/.bashrc'

# View markdown in terminal; requires pandoc + lynx installed
function mdn () {
  pandoc "$@" | lynx -stdin
}

alias +w='chmod +w'
alias +x='chmod +x'
alias a='alias'
alias ad='cd; a > a; . ~/.bash_profile; a > b; diff a b'
alias ag='alias | grep -i'
alias amend='git commit --amend'
alias asp='system_profiler'
alias cba='cat ~/.bash_aliases'
alias cp='cp -i'
alias cpr='cp -R'
alias cw='echo "----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8"'
alias dfh='df -h'
alias dush='sudo du -sh'
alias eject='drutil eject'
alias ejectm='sudo umount -f'
alias envg='env | grep'
alias eth='ifconfig -a'
alias f='finger'
alias ga='git add'
alias gca='git commit -a'
alias gcam='git commit -a -m'
alias gcl='git config --list'
alias gcm1='git commit -m'
alias gcn='git clean -n -d'
alias gco='git checkout'
alias gd='git diff -U0'
alias geth='ifconfig -a | grep -1 eth'
alias gmv='git mv'
alias grm='git rm'
alias gs='git status'
alias gsm='gs | more'
alias h='history'
alias hc='h | cut -c8-'
alias hg='h | grep -v grep | grep -i'
alias k='sudo kill -9'
alias l='ls -alFG'
alias l.='ls -d .*'
alias la='l [A-Za-z]*'
alias lb='lh | grep "[0-9][MG] "'
alias ld='l | grep /$'
alias le='ls -le'
alias lg='lt | grep'
alias lh='l -h'
alias ll='ls -l'
alias ls='/bin/ls -G'
alias lst='last -10'
alias lt='l -tr'
alias lvl='lt /var/log'
alias lx='lg "*"'
alias lz='l | sort -n -k5'
alias mq='mailq'
alias msd='mysqldump'
alias mv='mv -i'
alias ns='netstat'
alias p='ping -c4 -t4 -o'
alias pbc='arp -a | grep ^bc | sort'
alias pp='pull; push'
alias psa='ps -Ajeww'
alias psg='psa | grep -v grep | grep -i'
alias pull='git pull'
alias push='git push'
alias rmd='sudo rm -rf'
alias sci='~/bin/ssh-copy-id -i ~/.ssh/id_rsa.pub'
alias se='export TERM=vt102'
alias src='. ~/.bash_aliases'
alias st='sudo bash'
alias sue='sudo vi'
alias swu='sudo softwareupdate -l'
alias sync='rsync -pruv'
alias tf='tail -f'
alias tgz='tar gcvf'
alias tl='tail -20'
alias trt='traceroute'
alias untgz='tar xvf'
alias ut='uptime'
alias updatedb='sudo /usr/libexec/locate.updatedb'
